### ISSUE TITLE
Dashboard charts threadlock system

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#1105]
When rendering the dashboard with a high number of analytics results, the system becomes threadlocked. Determine how to optimize the Dashboard rendering process.

# Definition of done
- [ ] Performance audit has been performed on dashboard rendering sequence
- [ ] Enhancement proposal is given to the team
- [ ] Dashboard performance is improved to a reasonable experience

**Comment by frenchbread** [comment]
### Todo:

- [ ] Open a PR that fixes api-umbrella sync frequency
