### ISSUE TITLE
Document Apinf and API Umbrella high-level architecture

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#111]
We need to understand more about the mechanics of API Umbrella as related to the Admin API. Currently we only have a coarse understanding of the architecture and cannot be sure we are supporting all required functionality. We also need to plan our product architecture. Futhermore, we need to check optimal path to accessing API Umbrella functionality.

See [API Umbrella issue](https://github.com/NREL/api-umbrella/issues/152) list of methods and status of documentation.

Definition of done
---
* [ ] Produce document and diagram describing Web Admin (Rails app) architecture  as related to Admin API.
* [ ] Determine the feasibility of making REST calls directly to Gatekeeper (Node.js app) instead of the Web Admin.
* [ ] Produce an architecture document and diagram how to mirror API Umbrella architecture in Apinf code.

**Comment by bajiat** [comment]
Aseem

**Comment by ashakunt** [comment]
Yet to start on this.

**Comment by ashakunt** [comment]
This still goes to the backlog as I have been just able to configure the server with the latest installation from apiumbrella.io.

**Comment by ashakunt** [comment]
(or not really the backlog but the pre-planning; so that it moves to next sprint)

**Comment by bajiat** [comment]
@ashakunt Hi Aseem, can you tell me the status of this task?

**Comment by ashakunt** [comment]
Things achieved in this sprint for this task:

1. Running api-umbrella backend
2. Found out issue which can screw the backend
3. Clear understanding of how to setup the server and get it running for looking at various analytics
4. Able to configure custom apis in the umbrella and see how things work on that part
5. On scale of 1-10, understanding of the umbrella backend is: 4/10.
6. Learning basics of MongoDB


More understanding to be developed for:

1. MongoDB and its usage in api-umbrella
2. Why does the api-umbrella die on its own regularly (am i doing something wrong?) [I get 404 not found on ruby.apinf.com/admin quite sometimes]
3. Obtain understanding of rails app structure (I was trying to create a mapping between apiumbrella installation I have & api-umbrella code to understand how the server works and changing what affects what)

Not touched items:
1. How gatekeeper works

Unfortunately, I do not have any documents right now and most of the status I have prepared is from the linux history of commands I have been running on ruby.apinf.com.

**Comment by bajiat** [comment]
@ashakuntal Are you still interested on working on this task in Sprint 8? If yes, is 13 your current estimate for remaining effort?

**Comment by ashakunt** [comment]
@baijat, yes. I will finish this task in this sprint. Yes, 13 is the current estimate.

**Comment by bajiat** [comment]
@ashakunt Great! We checked all tasks that were in progress prior to sprint 8 planning, so that's why I wanted to check this task as well. I've re-labeled the task with Sprint 8 milestone now.

**Comment by bajiat** [comment]
@ashakunt Could you please add the status of this task before sprint review tomorrow (at 10 am)? Thanks!

**Comment by bajiat** [comment]
@ashakunt As part of pre-planning for sprint 9, we are moving this back to backlog, since we don't know the status. Maybe we'll keep this in backlog until the high priority tasks for sprint 9 have been completed.
