### ISSUE TITLE
Create API Umbrella user in all relevant collections

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#125]
When creating a new API Umbrella user in Apinf, create corresponding Meteor user. Also, create user object in API Umbrella Web.

Definition of done
---
* [ ] Write collection event function when inserting API Umbrella user into database.
* [ ] Within collection event, post API Umbrella user to API Umbrella Web.
* [ ] Store returned user object inside API Umbrella user object.
* [ ] Create corresponding Meteor user.
* [ ] Link API Umbrella user and Meteor user via id field.

**Comment by brylie** [comment]
Updated hours to 8.
