### ISSUE TITLE
Design communication channel between developers and API admins

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#149]
Design functionality for consumers to be able to give feedback about and feature requests for the API.

Definition of done
---
* [x] Brainstorm ideas for developer communication channel.
  * [x] Look for and document existing examples of developer communication channels.
* [x] Create design document for the communication channel feature.
* [x] Create wireframes for communication channel UI.

**Comment by kyyberi** [comment]
Something like Flowdock discussion flows?

**Comment by bajiat** [comment]
@elnzv Can you provide a status provide and commit any work in progress, even design pictures, to Github?

**Comment by elnzv** [comment]
Added wireframes to docs repo:
https://github.com/apinf/docs/blob/master/docs/design/%23149_communication_channel_apinf.png

**Comment by elnzv** [comment]
@bajiat please review, if you have any comments, let me know.

**Comment by bajiat** [comment]
@elnzv Just wondering if the API consumers want simply to give feedback or report problems using the APIs. Should the other API consumers be able to comment them as well?

**Comment by kyyberi** [comment]
comments +1

**Comment by elnzv** [comment]
@bajiat, This is about first, more features rich option, I think yes, other should see this feedback or report and be able to comment it.
Reason is in our philosophy of being open and working together. That's similar to Github, all issues are open. If the user wants to contact admin privately, a good way is to do it directly by email. We can leave space on feedback page for this information and admin's email. 

Talking about second option - all feedback or reports are private and will be visible only by admin. 

I have started implementing this ideas and started with simple direct messages to admin, without users' comments feature.  Later on we can add this feature.
