### ISSUE TITLE
Add new APIs to API Umbrella

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#177]
When saving an API backend in Apinf, also submit API backend to API Umbrella.

Definition of done
---
* [x] Test the API Umbrella Admin API via the Postman REST client
* [x] Demonstrate a successful API Backend insertion via the REST interface
* [x] Demonstrate the Meteor API Umbrella wrapper can insert API Backends successfully
* [ ] Add an AutoForm hook to POST API Backends on form submit success
* [ ] Write an automated test for AutoForm event

**Comment by brylie** [comment]
This issue is blocked by #196, as I cannot install the collection hooks package.

**Comment by brylie** [comment]
I tried this again, and could not run the collection.before.insert() method. I am not sure why it is not available, as I defined it within the collection javascript file, directly after the schema definition.

**Comment by brylie** [comment]
I would like to work with a pair programming partner on this issue. One possible solution would be to use the ApiBackend autoform hook to integrate the form with API Umbrella.

**Comment by bajiat** [comment]
Let's discuss the pair programming session in the standup.

**Comment by brylie** [comment]
Illya and I re-installed API Umbrella, and configured the SSL certificate. HTTPS now works at https://umbrella.apinf.io

**Comment by brylie** [comment]
I am still having trouble posting a new API Backend to the API Umbrella Admin API, via the Postman REST client. I have opened an [issue requesting a working example](https://github.com/NREL/api-umbrella/issues/165).

**Comment by ashakunt** [comment]
@brylie, I just added a minimum example for creating a backend request at: https://github.com/NREL/api-umbrella/issues/165, please check that.

**Comment by brylie** [comment]
Thanks @ashakunt
