### ISSUE TITLE
Ensure each Apinf user has one and only one associated API Umbrella user

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#186]
Currently, our Admin dashboard allows creation of new API Umbrella users. However, API Umbrella users should be created when Apinf user is created rather than in a separate process.

Definition of done
----
* [x] Remove API Umbrella user widget from Admin dashboard.
* [x] Create collection hook to create new API Umbrella user when [creating Apinf user](https://github.com/apinf/api-umbrella-dashboard/blob/master/server/accounts.coffee).
* [x] Make sure Apinf users are only linked to one API Umbrella user.

**Comment by brylie** [comment]
I have removed the form widget. The collection hook exists on user creation. The schema only allows one apiUmbrellaId field per user.

**Comment by brylie** [comment]
We verified that the user is being created and cross-linked in our [accounts.coffee#52-72](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/accounts.coffee#L52-L72). We need a new task to unit test the aforementioned lines.

**Comment by brylie** [comment]
I created an issue (#202) to unit test the accounts.coffee.
