### ISSUE TITLE
Investigate rate limiting in API Umbrella

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#220]
Rate limiting already exists in API backend schema. We need to ensure API admins are able to rate limit based on API Umbrella. Determine what rate limiting functions API Umbrella supports. Document differences between API Umbrella rate limiting and desired Apinf rate limiting features.

Definition of done
---
* [x] Create a list of desired Apinf rate limiting methods, such as time, geography, user, frequency
* [x] Create a list of existing Api Umbrella rate limiting options
* [x] Compare the two lists to determine project plan
* [x] Make feature requests to API Umbrella for missing rate limiting methods, if necessary

**Comment by JuusoV** [comment]
Document
https://apinf.hackpad.com/Rate-limiting-oWHZLO0GYwA
