### ISSUE TITLE
Create subdomain umbrella.apinf.io and deploy API Umbrella

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#304]
We want to deploy the latest version of API Umbrella on a sub-domain of apinf.com. This includes configuring the SSL certificate.

## Task
* [x] Create a sub-domain *umbrella.apinf.io*
* [x] set up a virtual machine with 1Gb RAM, 20 Gb HDD
* [x] Install the latest version of API Umbrella
* [x] Configure the SSL certificate for HTTPS access

**Comment by elnzv** [comment]
@ashakunt what is the status now? we need ti install it ASAP, if you are busy whit something else, let us know, we will do it ourselves.

**Comment by ashakunt** [comment]
@elnzv, please go ahead. I somehow missed this earlier and I am sorry for that. Or else, I can do the rest of the stuff (Installing API umbrella, Configure SSL) by EOD today along with configuring basic firewall ports. Please let me konw

**Comment by ashakunt** [comment]
For that purpose, please pass me on the credentials. Further, please be advised, the 1GB ram will not be sufficient for the umbrella installation. I would suggest at least 2GB ram. I have tried a similar installation for ruby.apinf.com which did not work and the system was very slow.

1.5GB free memory
1GB free swap

**Comment by elnzv** [comment]
Okay, now it's done.
https://umbrella.apinf.io

**Comment by jykae** [comment]
@elnzv @ashakunt I have done Umbrella deployment for APIKA. When I publish API configuration, Umbrella rewrites configuration so that I cannot access to /admin route. We don't have SSL certificate yet, so could this be related to it? Did you have similar problem?

**Comment by elnzv** [comment]
Yes, you should have SSL certificate. That was an issue when I was
deploying.

On Tue, 10 Nov 2015 at 12:24 Ville Jyrkkä <notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> @ashakunt <https://github.com/ashakunt>
> I have done Umbrella deployment for APIKA. When I publish API
> configuration, Umbrella rewrites configuration so that I cannot access to
> /admin route. We don't have SSL certificate yet, so could this be related
> to it? Did you have similar problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apinf/api-umbrella-dashboard/issues/304#issuecomment-155380567>
> .
>
-- 

Illya Nizyev | www.nzv.nz

**Comment by brylie** [comment]
Please also open an issue on API Umbrella issue tracker, if it doesn't exist. This will help other users, including potentially Apinf clients.

On 10 November 2015 12:26:39 EET, illya nizyev <notifications@github.com> wrote:
>Yes, you should have SSL certificate. That was an issue when I was
>deploying.
>
>On Tue, 10 Nov 2015 at 12:24 Ville Jyrkkä <notifications@github.com>
>wrote:
>
>> @elnzv <https://github.com/elnzv> @ashakunt
><https://github.com/ashakunt>
>> I have done Umbrella deployment for APIKA. When I publish API
>> configuration, Umbrella rewrites configuration so that I cannot
>access to
>> /admin route. We don't have SSL certificate yet, so could this be
>related
>> to it? Did you have similar problem?
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/apinf/api-umbrella-dashboard/issues/304#issuecomment-155380567>
>> .
>>
>-- 
>
>Illya Nizyev | www.nzv.nz
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apinf/api-umbrella-dashboard/issues/304#issuecomment-155381064

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jykae** [comment]
Suggestion for Umbrella: https://github.com/NREL/api-umbrella/issues/192
This is mentioned in one sentence in documentation, but behaviour without SSL certificates in production is not stated.
