### ISSUE TITLE
Add Managers field to API backend schema

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#325]
Add API managers field to API backend schema and implement basic permissions for API managers.

### Definition of done
* [x] Add the managers array field to the API backend schema.
* [x] Create publication for API backends managed by a given user.
* [x] Create subscription for use in client templates.
* [x] Create client template to display list of APIs managed by given user.
* [x] Create route to display API Manager template
* [x] When creating API backend, add current user ID to the API managers array.
* [x] Create allow/deny rules so that only API managers can update or delete their managed APIs.
