### ISSUE TITLE
Create a settings page for Apinf configuration options

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#327]
For organizations to host Apinf as a service, they need an easy way to configure the settings like mailgun. Create a settings page to hold current and future configuration options as well as a collection to store the configs.

# Research
* [x] Look for existing settings/ configuration pages in open-source Meteor projects
* [x] Look for configuration page examples in other web applications
* [x] Create a design document and list the solutions you found

# Design
* [x] Add a description of the configuration page to the design document
* [x] Create one or more wireframes to demonstrate the intended design (*do not skip this step*)

# Implement
* [x] Create a collection to store configuration settings
* [x] Create one or more templates to hold configuration forms
* [x] Create a schema to define configuration settings
* [x] Use AutoForm to build one or more configuration forms on the settings page(s)

Co-pilot: @brylie

**Comment by bajiat** [comment]
Blocks #502.

**Comment by bajiat** [comment]
@frenchbread You were interested in this task. I have assigned it to you and estimated the size according to your estimation.

**Comment by brylie** [comment]
@elnzv status report? Also, please provide wireframes before writing code.

**Comment by brylie** [comment]
Check out how the [Dominus game](https://github.com/dan335/dominus) (which is built with Meteor) handles Settings. It seems to have a settings collection, where each setting is stored as a separate document. Settings can then be [retrieved using `Settings.findOne({name: "settingName"});`](https://github.com/dan335/dominus/blob/master/server/accounts.js#L21).

**Comment by jykae** [comment]
I wonder if this Settings is only related to frontend settings, OR also to Settings Object in ApiBackendSchema that I'm working in #503 and #504 ? 

If the answer is Yes to latter one, I think we should co-operate with this one @elnzv

**Comment by elnzv** [comment]
[wireframes added](https://github.com/apinf/docs/blob/master/docs/design/%23327_settings_page_apinf.png)

![327_settings_page_apinf](https://cloud.githubusercontent.com/assets/7489044/10837018/7c86543a-7ebd-11e5-9000-181dc903fe36.png)

**Comment by bajiat** [comment]
Would it be possible to move the Import button to the top, if the purpose is to populate the fields with settings from existing settings.json? Or should the fields be updated automatically, if there is a settings.json? Or is that file even needed any more?

**Comment by elnzv** [comment]
@bajiat, yes, button is optional. If we still stay with settings.json file - the best approach is to check it on startup and update collection and form with new values.

**Comment by brylie** [comment]
I think we should plan for grouping, and possibly tabs. I.e. our settings will have natural groupings, such as email authentication, Github application settings, etc.. Not every group of settings will be relevant to all deployments.

**Comment by elnzv** [comment]
Can't access ApiUmbrellaWeb object on startup.
I need to be able to define this somewhere outside the package.
@brylie has already started working on this.

**Comment by bajiat** [comment]
@elnzv We are proposing the two interrelated settings tasks: 327 and 74 for you.

**Comment by elnzv** [comment]
Here is how I think it should work:

- if starting without settings.json and there is nothing in Settings collection - show form to enter needed values. Template with form can be rendered on startup before any sync. After submission meteor will look for required values in Settings collection,
- if starting with settings.json file parse it and duplicate it to Settings collection (additionally we can show message that now user can edit his settings through UI and start without --settings flag);

Blocking: mailgun dependencies, user can't be registered without mailgun being configured.

**Comment by elnzv** [comment]
Working branch: https://github.com/apinf/api-umbrella-dashboard/tree/feature/admin-settings-page

For now have already this UI for settings page:

![screencapture-localhost-3000-settings-1448440697861](https://cloud.githubusercontent.com/assets/7489044/11392188/bb791184-9360-11e5-8c23-1176b5d51feb.png)

**TODO/in progress:** divide settings into sections with help texts and placeholder examples.

**Comment by brylie** [comment]
@elnzv status update?

**Comment by elnzv** [comment]
- Added sections, new placeholders:

![screencapture-localhost-3000-settings-1448594770267](https://cloud.githubusercontent.com/assets/7489044/11433574/798e3836-94c7-11e5-92c1-9a5e94824593.png)

- Added logic (formType) to choose "insert" or "update".

- Now on startup if application starts without --settings it renders **/settings**:
```js
if ( Settings.findOne() ) {
        this.next();
      } else {
        this.redirect('/settings');
        this.next();
      }
```
But still can't pause sync. Idea is somehow to wait after redirect and only when data is added continue with sync.

**Comment by brylie** [comment]
@elnzv where is your working code for this task? The 'settings' branch has a last commit 5 days ago. I am asking, because I just found the following in the [SimpleSchema docs](https://github.com/aldeed/meteor-simple-schema#schema-keys):

> A basic schema key is just the name of the key (property) to expect in the objects that will be validated. If necessary, though, you can use string keys with mongo-style dot notation to validate nested arrays and objects.
> 
> For example:
>
> ```JavaScript
> MySchema = new SimpleSchema({
>    "mailingAddress.street": {
>       type: String
>   },
>    "mailingAddress.city": {
>        type: String
>    }
>});
> ```
> To indicate the presence of an array, use a `$`

Basically, you don't need `$` in your schema, because that implies an array of objects. So, if you remove the `$`s, your settings data may validate.

**Comment by brylie** [comment]
@elnzv you may also be able to set `blackbox: true` on the settings objecs:

> If you have a key with type Object, the properties of the object will be validated as well, so you must define all allowed properties in the schema. If this is not possible or you don't care to validate the object's properties, use the `blackbox: true` option to skip validation for everything within the object.
