### ISSUE TITLE
Add "Default Response Headers" field to Add API Backend form

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#503]
The "Default Response Headers" field is not currently available on the Add API Backend form. This is inconsistent with the API Umbrella system.

Help text should read:
> Define header values that will be set in the response regardless of whether the header is already set in the response.
>
> For example, to set default CORS headers on all responses that don"t explicitly set their own CORS headers:
>
> `Access-Control-Allow-Origin: *`

# Task
## Verify existing field in API Umbrella
* [x] Verify "Default Response Headers" field design on API Umbrella API Backend form
* [x] Make note of field design, location on form, etc

## Implement field in Apinf
* [x] Update ApiBackends schema to include "Default Response Headers" field
* [x] Ensure schema definition matches API Umbrella field name and validation settings
* [x] Add field to Add API Backend form

## Test new field
* [x] Manually test that form submits both with and without field input
  * [x] Ensure that submitted data is present in API Umbrella, i.e. that it validates

**Comment by brylie** [comment]
Co-pilot: @elnzv

**Comment by jykae** [comment]
According to Umbrella field design "Default response headers" comes after "Rate limit" field. In Apinf "Rate limit" field seems to be "Rate limit mode".

**Comment by jykae** [comment]
"Ensure schema definition matches API Umbrella field name and validation settings", how I find Umbrella validation settings?

**Comment by jykae** [comment]
Umbrella Admin API, http://apiumbrella.io/docs/admin-api/#!/api/post_api_umbrella_v1_apis

There seems to be a common problem how to create subobjects/subschemas inside Schema, https://github.com/aldeed/meteor-simple-schema/issues/357

Below the response I get back when creation is successful:

Submitting Backend to API Umbrella.
I20151028-14:23:48.234(2)? { api:
I20151028-14:23:48.235(2)?    { backend_host: 'xxx.com',
I20151028-14:23:48.235(2)?      backend_protocol: 'http',
I20151028-14:23:48.235(2)?      balance_algorithm: 'least_conn',
I20151028-14:23:48.235(2)?      created_at: '2015-10-28T12:21:00Z',
I20151028-14:23:48.235(2)?      created_by: 'xxx',
I20151028-14:23:48.235(2)?      deleted_at: null,
I20151028-14:23:48.235(2)?      frontend_host: 'xxx.com',
I20151028-14:23:48.235(2)?      name: 'Just testing',
I20151028-14:23:48.235(2)?      servers: [ [Object] ],
I20151028-14:23:48.235(2)?      settings:
I20151028-14:23:48.236(2)?       { allowed_ips: null,
I20151028-14:23:48.236(2)?         allowed_referers: null,
I20151028-14:23:48.236(2)?         anonymous_rate_limit_behavior: null,
I20151028-14:23:48.236(2)?         append_query_string: null,
I20151028-14:23:48.236(2)?         authenticated_rate_limit_behavior: null,
I20151028-14:23:48.236(2)?         disable_api_key: null,
I20151028-14:23:48.237(2)?         error_data: null,
I20151028-14:23:48.237(2)?         error_templates: null,
I20151028-14:23:48.237(2)?         http_basic_auth: null,
I20151028-14:23:48.237(2)?         pass_api_key_header: null,
I20151028-14:23:48.237(2)?         pass_api_key_query_param: null,
I20151028-14:23:48.238(2)?         rate_limit_mode: null,
I20151028-14:23:48.238(2)?         require_https: null,
I20151028-14:23:48.238(2)?         require_https_transition_start_at: null,
I20151028-14:23:48.238(2)?         required_roles: null,
I20151028-14:23:48.238(2)?         error_data_yaml_strings: {},
I20151028-14:23:48.239(2)?         headers_string: '',
I20151028-14:23:48.239(2)?         default_response_headers_string: '',
I20151028-14:23:48.239(2)?         override_response_headers_string: '',
I20151028-14:23:48.239(2)?         id: 'xxx' },
I20151028-14:23:48.239(2)?      sort_order: 14,
I20151028-14:23:48.239(2)?      updated_at: '2015-10-28T12:21:00Z',
I20151028-14:23:48.239(2)?      updated_by: 'xxx',
I20151028-14:23:48.239(2)?      url_matches: [ [Object] ],
I20151028-14:23:48.239(2)?      version: 1,
I20151028-14:23:48.240(2)?      id: 'xxx',
I20151028-14:23:48.240(2)?      creator: { username: 'xxx@yyy.com' },
I20151028-14:23:48.240(2)?      updater: { username: 'xxx@yyy.com' } }
} }

I removed domains, ids & emails from the attached response. Tried creating settings Object in schema with "default_response_headers_string" String type. 

If "settings" Object has only String  "default_response_headers_string", API gives back response 500, "Something went wrong." To get validation through "settings" Object must be required, not optional.  I research further...

**Comment by jykae** [comment]
I try to break huge ApiBackendsSchema to manageable pieces in the same way they are in Umbrella model. Using this aldeed/meteor-simple-schema#357 as reference. 

However this will be then refactoring the whole ApiBackendsSchema, as most of the data never passes to the backend, just the fields that are in "Api"-section of Umbrella and basic types like String.

**Comment by jykae** [comment]
Let's forget that refactoring. Traced issue in sub-settings structure: https://github.com/NREL/api-umbrella/issues/185

But we can't wait that to be improved. So just following more carefully the tree structure: "sub-settings" -> "settings" -> "default_response_headers_string"

**Comment by jykae** [comment]
Correction! There is also "settings" Object outside "sub-settings". 
So I followed "settings" -> default_response_headers_string" path and got it working. Cleaning up & making PR.

Check out the way how to nest Object inside other Schema with SimpleSchema :)

**Comment by jykae** [comment]
Omg, I forgot the "help text". Will fix it Tomorrow(tm).
