### ISSUE TITLE
Create CONTRIBUTING.md file in project root

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#521]
New developers may benefit from a brief description of how they can get involved. This description is often provided in a file called CONTRIBUTING. Github will look for a file called `CONTRIBUTING.md` and link new developers to that document when they create a pull request.

# Task
* [x] Create CONTRIBUTING.md in project root folder
* [x] Move "Getting Started" and other relevant details from README.md to CONTRIBUTING.md
* [ ] Move contents from existing contributing.md in docs repository  to the new CONTRIBUTING.md in project root folder and remove the original from docs repository.
* [ ] Add useful sections inspired from other CONTRIBUTING.md files (see below)

# Reference
## General reference/discussion
* Github [Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
* Github [Contributing Guidelines](https://github.com/blog/1184-contributing-guidelines)
* Hacker News: [Ask HN: What Are Some Good GitHub "Contributing" Examples?](https://news.ycombinator.com/item?id=4828165)

## Specific project CONTRIBUTINg.md examples
There are a few good CONTRIBUTING.md examples:
* [Angular](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md)
* [Atom editor](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
* [Bootstrap](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)
* [Gitlab](https://github.com/gitlabhq/gitlabhq/blob/master/CONTRIBUTING.md)
* [Node.js](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md)
* [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/CONTRIBUTING.md)

For a general list of files, see the [Github search for CONTRIBUTING.md](https://github.com/search?utf8=%E2%9C%93&q=contributing.md)

**Comment by kyyberi** [comment]
+1
