### ISSUE TITLE
Create a new API Umbrella user on Apinf sign-up

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#68]
Create a request to API Umbrella generating an API user  whenever a new user signs up to Apinf. Add the key to Apinf database. Note that every Apinf user should be linled to an API Umbrella user via id.

User story: As Minh (API consumer), I want to get the API keys.

Definition of done:
* [x]  Store API Umbrella users in Apinf database
* [x]  Linking between data collections
* [x]  Function (collection helper) to link relationship

**Comment by frenchbread** [comment]
So far, I was able to create an API Umbrella User on Apinf sign up. At the same time apiUmbrellaUser's ID is linked to apinf user's object as well as API Key field is now visible with real api key on profile settings page. Here is the branch I am working on - [link](https://github.com/apinf/api-umbrella-dashboard/tree/feature/api-key-field-userprofile).

There are two issues that do not affect functionality but still can be solved:
- [ ] When user is being created on Apinf the API Umbrella user object looks like:

```javascript
apiUmbrellaUserObj = {
      "user":{
        "email": user.emails[0].address,
        "first_name": "First Name",
        "last_name": "Last Name",
        "terms_and_conditions":true
      }
    }
```
...meaning that there is no way to get real user's first name and last name because Apinf user object has just **email** after signing up without social services.

- [ ] Do we need create apiUmbrella User in Apinf database instantly after user is created on apiUmbrellaWeb or we can wait for daily sync update handled by cron tasks?
