### ISSUE TITLE
Exporting and importing i18n JSON files to/from OneSky

### ISSUE THREAD

**Issue by kyyberi** [apinf/api-umbrella-dashboard#692]
Ensure that translation managers can easily import i18n files into OneSky. Also, ensure that exported OneSky translation files adhere to requirements of our i18n package:

* [tap:i18n documentation](https://github.com/TAPevents/tap-i18n)

# Task
* [x] Make sure i18n files are valid JSON. 
  * [x] No comments
  * [x] Passes JSON validation
* [x] Ensure that files exported from OneSky are renamed every time to match the required naming convention:
  * end with:  `[language-code].i18n.json`
* [ ] Alphabetize translation tokens in file

## Original report
> Source translation file /i18n/en.i18n.json is not valid. Comments are not allowed in JSON. Currently there is 

>```
>{
>
>  /*Config*/
>  "configName": "Apinf",
>  "configTitle": "Build custom APIs. Fast.",
>  "configSubtitle": "Create custom API mashups, really quick.",
>```
>
>I suggest reformatting the JSON and one option is to make current comments as the group "element" for each collection. 
>
>If you insist on keeping comments, you could use https://github.com/getify/JSON.minify to strip out comments before taking it to production/use.

**Comment by kyyberi** [comment]
Since it's not valid, current online translation management environments do not accept it as source

**Comment by kyyberi** [comment]
Example https://gist.github.com/kyyberi/dc304c869ef706d737c5

**Comment by kyyberi** [comment]
If translation management suggested at #691 is the way to go, we should rename base file to en.json for the sake of simplicity. The translation management exports files with language code .json for example finnish is fi.json. Not mandatory to change but slimlines the translation file management process just a little bit.

**Comment by brylie** [comment]
Great suggestions. I am adding this and #691 to our upcoming sprint planning.

**Comment by brylie** [comment]
@jykae is currently importing the translations from OneSky. There is some restructuring necessary, so that the file is compatible with our i18n framework. This likely stems from the comments in the original en.i18n.js, so we will need to remove comments as part of this task (as already suggested).

**Comment by jykae** [comment]
@brylie PR #778 Fixes hyphens to underscores and adds Finnish translations from OneSky.

**Comment by jykae** [comment]
Validated with JSONLint.

![validjson](https://cloud.githubusercontent.com/assets/293452/12452032/16bb8dc8-bf95-11e5-9e55-0b6a20cfff88.png)
