### ISSUE TITLE
Create a form or button for importing basic API configuration (API Umbrella)

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#72]
As Harri (API administrator), I want to import API configurations to Apinf

Definition of done
----------------------------
* [ ] Create basic template for API configuration upload.
* [ ] Add Bootstrap button to API configuration upload template.
* [ ] Create file system collection to store API configuration files.
* [ ] Create template logic e.g. helper and event to upload file, when button is clicked.

**Comment by bajiat** [comment]
Illya, will you be able to finish this task in the next two days? I'm asking this, because we are considering a related task to next sprint.

**Comment by brylie** [comment]
Added pull request.
