### ISSUE TITLE
Create a form for choosing basic brand elements, for example, colors and logo

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#74]
For the purpose of re-branding / whitelabeling Apinf, there should be an option for modifying colors and logos. This may be related to #327.
User story: As Harri (API administrator), I want to add brand elements to our organisations Apinf installation

# Task

## Choose
* [x] Choose what UI elements to make editable through configuration page
* [x] Determine how to make UI elements editable
  * [x] E.g. template variables for CSS colors
  * [x] E.g. template variable for logo

# Design
**Do not skip this step**
* [x] Create design document describing the intended configuration page
* [x] Create wireframe for intended configuration section design
* [x] Include wireframe in design document and this issue
* [x] Publish wireframe(s) in design documentation section of project sourcecode

# Implement
* [x] Add a branding section / tab / page to the configuration page created in #327
* [x] Create a schema for branding elements
  * [x] Colors
  * [x] Logo
* [x] Create necessary collection(s)
  * [x] FS collection for branding image
  * [x] Field(s) in Configuration collection for branding

**Comment by bajiat** [comment]
@elnzv You are the expert in the style elements, so this should probably be your task as well. What do you think? Can you estimate the size, if this task still fits in this sprint.

**Comment by elnzv** [comment]
Taking this task also. It will be last on the priority list, is that fine, @bajiat?

**Comment by bajiat** [comment]
@elnzv Yes, that is exactly as it should be, this has the lowest priority.

**Comment by bajiat** [comment]
@elnzv I'm moving this task to pre-planning for next sprint and unassigning it.

**Comment by brylie** [comment]
Sprint 15 co-pilot is @frenchbread

**Comment by elnzv** [comment]
[wireframes added](https://github.com/apinf/docs/blob/master/docs/design/%2374_branding_page_apinf.png)

![74_branding_page_apinf](https://cloud.githubusercontent.com/assets/7489044/10837494/b447857e-7ec2-11e5-8126-a4bbd98a5864.png)

**Comment by brylie** [comment]
@elnzv status update?

**Comment by elnzv** [comment]
For now I have page, collections, logic for changing colors and logo.
Still need to think what elements are for color changing (suggestions are welcome).
Before sprint review will have PR opened.

**Comment by elnzv** [comment]
Now users can upload their own image for logo.
TODO:
- define who has right to change logo
- add method to remove (reset to default) logo

AdminLTE has several options for color schemas (skins)
We can use them for now, since they are complete and changes can be applied to almost all elements. 

I think #327 is related, at least layout, I have created a side menu for different app settings, like branding, config, account etc.

Want to keep working on this task next sprint. Need around 5 hours to finish it.

**Comment by elnzv** [comment]
Found a way how to toggle AdminLTE skins:

```js
Template.AdminLTE.helpers({
 skin: function () {
    return 'blue';
  }
});
```
It changes skin class, but not css.
Can't figure out what is the problem.
Created an issue https://github.com/meteor-factory/meteor-admin-lte/issues/18

**Comment by brylie** [comment]
Can we force a page reload once the setting is saved?

On 4 December 2015 07:19:47 EET, illya nizyev <notifications@github.com> wrote:
>Found a way how to toggle AdminLTE skins:
>
>```js
>Template.AdminLTE.helpers({
> skin: function () {
>    return 'blue';
>  }
>});
>```
>It changes skin class, but not css.
>Can't figure out what is the problem.
>Created an issue
>https://github.com/meteor-factory/meteor-admin-lte/issues/18
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apinf/api-umbrella-dashboard/issues/74#issuecomment-161879872

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elnzv** [comment]
Even if I do it manually, it doesn't work.
I think it changes class but not styles. Styles are changing in different place.

**Comment by brylie** [comment]
@elnzv I was able to get AdminLTE to change theme dynamically, without any AdminLTE packages. Please see my [demonstration repository](https://github.com/apinf/meteor-adminlte-color-toggle) for some working code.

You can use this code as a basis for your theme configuration option, by pulling the value from the settings collection.

**Comment by elnzv** [comment]
Now I have AdminLTE skins options functionality in place.
Before I create a pull request, one last thing is left. That's resetting (removing) uploaded logo.

**Comment by frenchbread** [comment]
While reviewing:

1. Is it possible to make a logo be located in the middle vertically? (Now it's aligned by the top edge) Otherwise provide a user with dimensions needed for logo image.

    <img width="300" alt="screen shot 2015-12-17 at 21 44 05" src="https://cloud.githubusercontent.com/assets/2122679/11870084/e99109e2-a507-11e5-8ec7-354d1638678f.png">

2. File extension is not checked, so I was able to upload `.zip` file.

3. Color schema is not applied when the selection in the select-box changes.

**Comment by frenchbread** [comment]
Suggested changes and fixes are committed to #711.

**Comment by brylie** [comment]
Great work @frenchbread. I have self-assigned to the PR, and will review tomorrow.
