### ISSUE TITLE
Determine how API Umbrella collects rate limiting data

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#83]
Determine how API Umbrella collects rate limiting data

Definition of done
--------------
* [x] Contact original designers about the logic API Umbrella data schema for rate limit field
* [x] Description of API Umbrella data schema for rate limit field
* [x] UI wireframe for Apinf rate limit field in relevant view (API Configuration)

**Comment by JuusoV** [comment]
Posted Issue #147 https://github.com/NREL/api-umbrella/issues/147

**Comment by JuusoV** [comment]
Reduced estimate from 8 hours to 5 hours.
Tasks to do:

- Wireframe from UI with thee Rate limit field
- Document on Hackpad how the rate limit works in the rails according to the response I get.

**Comment by JuusoV** [comment]
The original design is pretty much the wireframe. Material design branding will be added on this.

**Comment by JuusoV** [comment]
Reduced time estimate from 5 hours to 3.

**Comment by JuusoV** [comment]
Status: Still waiting reply. Other tasks in regards to this are done.

**Comment by brylie** [comment]
@JuusoV great work!
