### ISSUE TITLE
Finish writing API Umbrella wrapper functions for REST package

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#84]
Write wrapper functions for each [API Umbrella Admin API](http://apiumbrella.io/docs/admin-api/) method. Specifically, the following need to be created:

Users
---
* [x] get all users
* [x] create new user
* [x] get user
* [ ] update user

API Backends
---
* [x] get all api backends
* [ ] create new api backend
* [x] get api backend
* [ ] update api backend

Admin Accounts
---
* [x] get all admins
* [ ] create new admin
* [x] get admin
* [ ] update admin
